// <auto-generated />
namespace LTQLWEB2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtableKHACHHANG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableKHACHHANG));
        
        string IMigrationMetadata.Id
        {
            get { return "202011271034594_add-table-KHACHHANG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
