// <auto-generated />
namespace LTQLWEB2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetableNHANVIEN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetableNHANVIEN));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261851416_update-table-NHANVIEN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
